// Definitions generated from Simple English Wiktionary via Kaikki on 2026-05-25.
// The source data is derived from CC-BY-SA and GFDL licensed Wiktionary content.
// Words without a confident Simple English Wiktionary match keep their local fallback in vocab.ts.
export const SIMPLE_WIKTIONARY_DEFINITIONS: Record<string, string> = {
    "abandon": "If you abandon something, you go away from it with no plan to return.",
    "above": "The above comment, discussion, argument, etc. is one higher than or coming before something.",
    "abrupt": "An abrupt action is one that is sudden, or not expected.",
    "abundant": "If something is abundant, then there is a lot of it.",
    "accelerate": "If you are driving and you accelerate your car, you make it go faster.",
    "access": "If you have access to something, you can use it, look at it, enter it, etc.",
    "accident": "Accident means something that happens without a plan; unintentionally; inadvertently.",
    "accurate": "Something accurate is correct or exact.",
    "achieve": "If you achieve success or a goal, you have completed what you planned to do or have a good result.",
    "achievement": "An achievement is something that is or was achieved.",
    "acknowledge": "If you acknowledge a fact or a situation, you accept or admit that it is true or that it exists.",
    "acquire": "If you acquire something, you buy or get it.",
    "act": "If you act in some way, you do something that makes people think you are that way.",
    "add": "If you add x to y, you put x and y together.",
    "address": "An address is the location where a building is or where a person lives.",
    "adequate": "If something is adequate, it is good enough.",
    "adjust": "If you adjust something, you change it a little so that it fits or works better.",
    "administrate": "If you administrate something, you organize and manage it.",
    "adopt": "If you adopt something, you choose and begin to use it instead of what you used in the past.",
    "advice": "If you give someone advice, you tell them what you think they should do.",
    "affect": "If x affects y, then x causes a change in y.",
    "afford": "If you can afford something, you have enough money or resources to buy it or do it.",
    "after": "Later in time.",
    "again": "Once more.",
    "age": "Something's age is how long it has existed or been alive; how old something is.",
    "aggressive": "Making attacks or assaults that are not just.",
    "ago": "At an earlier time.",
    "agree": "When two people agree about something, they have the same ideas. They both think the same things are true.",
    "air": "Air is a mixture of gases. It has no color or odor (smell)",
    "alert": "To be alert is to be awake; attentive",
    "allocate": "If you allocate something, you set it aside or plan to use it for a particular purpose. The term is often used with money or resources.",
    "alter": "If you alter something, you change it, usually in a small way.",
    "alternate": "To alternate is to take turns.",
    "alternative": "An alternative approach, way, source, etc. is not the usual one.",
    "altitude": "Height measured from sea level.",
    "always": "If something always happens, it happens at all times or every time.",
    "amend": "If you amend a law, statement, or piece of writing, you change it to make it better or fix a mistake.",
    "analyse": "If you analyse something, you study it carefully to understand it, often to see what it is made of.",
    "ancestor": "An ancestor is a person from whom one is descended. A very similar word is forebear.",
    "ancient": "Very old, usually hundreds or thousands or millions of years old.",
    "animal": "An animal is any living thing that can move. People are not animals, but are said to be animals, under the scientific definition. .",
    "annual": "If something is annual, it happens every year.",
    "answer": "An answer is something that someone says after another person asks (says) a question.",
    "antagonist": "An antagonist is an opponent or enemy.",
    "anticipate": "If you anticipate something, you think or do something about it before it happens.",
    "antonym": "A word that means the opposite of another word.",
    "anxious": "To be anxious, you are worried or scared about what might happen in the future.",
    "apparent": "If something is apparent, it is easy to see, realise or understand.",
    "appeal": "An appeal is a strong or official request.",
    "approach": "An approach is a way of doing something.",
    "appropriate": "If something is appropriate, it matches the situation.",
    "approximate": "An approximate number, length, time, etc. is close to the real one but may not be equal to it.",
    "arctic": "The Arctic is the region of the Earth surrounding the North Pole.",
    "area": "An area is a piece of land or space.",
    "arena": "An arena is a place where sports, entertainments, and other public events take place. It has seats around it where people sit and watch.",
    "arrange": "If you arrange something, you put it in order or you organise it.",
    "arrest": "If something arrests something else, it stops it.",
    "arrive": "If you arrive somewhere, you come to that place, usually the place that you planned to go to.",
    "ascend": "If you ascend something, then you go up it.",
    "ask": "To ask is to look for an answer to a question by saying it.",
    "aspect": "An aspect is a view of something, often something non-physical, such as an idea or a problem.",
    "assess": "If you assess a person, idea, skill, process, etc., you judge or measure them.",
    "assist": "If you assist someone, you help them.",
    "assume": "If you assume something, you think or believe something without having enough information to know that it's true.",
    "astound": "If you are astounded, you are shocked or greatly surprised.",
    "attempt": "An attempt is a try at something, usually something difficult",
    "attention": "If you pay attention to something, you focus your mind on it.",
    "attentive": "If a person or animal is attentive, it is trying hard to notice things.",
    "attitude": "Your attitude is your feelings and opinions, especially when your actions show how you feel.",
    "attract": "If something attracts you, it makes you interested in it.",
    "attribute": "An attribute is a part, feature, or characteristic.",
    "authority": "To have authority means to have the power to make a decision.",
    "available": "If something is available, it exists and you can use it.",
    "avalanche": "An avalanche is a large body of snow and ice sliding down a mountain side quickly.",
    "average": "An average is a measure in the middle of several numbers.",
    "avoid": "When you avoid something, you stay away from it or you don't do it.",
    "aware": "If you are aware of something, you know about it.",
    "back": "The back is the rear part of something; it is the part in the other direction from the front.",
    "baggage": "Another word for luggage; bags and other containers that people use to carry things when they travel. Also, the things (most often clothes) carried in the bags.",
    "balance": "If you balance something, you make it have equal amounts all around.",
    "ban": "A ban is a rule that stops something from happening; a prohibition from something.",
    "base": "Something's base is its lower part; the solid part that touches the floor or touches the earth and keeps the other parts of the thing up.",
    "basic": "When something is basic, it is simple.",
    "bed": "A piece of furniture to sleep on.",
    "before": "If x happens before y, x happens first and y happens second.",
    "begin": "When you begin something, you start to do the first part of a longer action.",
    "behind": "When something is behind a second thing, the first thing is in back of the second.",
    "benefit": "A benefit is something good that comes from something else.",
    "between": "If x is between y and z, y is on one side of x and z is on the other side.",
    "beverage": "A beverage is a liquid, such as milk, juice or coffee, that can be drank.",
    "big": "If something is big, it is large in size; tall, wide, long, or fat.",
    "blend": "If you are blending something, you are mixing it so that they combine together.",
    "blizzard": "A blizzard is when a lot of snow falls with strong winds that make it hard to see very far.",
    "blossom": "A blossom is a flower of a plant that will become a fruit.",
    "blue": "Colored blue.",
    "board": "A board is a flat surface.",
    "body": "A body is the main part of a person, animal, physical object, or organisation.",
    "bold": "If someone is bold, that means they are brave and willing to take risks.",
    "bond": "A bond is a connection between two people because of love or friendship.",
    "border": "The border of a country is the edge of the country: the place where that country touches another country.",
    "both": "When there are two things, both is the first thing and the second thing.",
    "bounce": "To bounce is to change the direction of motion after hitting an object.",
    "boy": "A boy is a male child or teenager; someone who is not a man yet.",
    "brave": "If you are brave, fear will not stop you.",
    "brief": "If something is brief, it is for a short time.",
    "bring": "Sometimes bring means carry something with you to a place where that someone can receive it.",
    "budge": "If something budges, it moves from a fixed position.",
    "build": "If you build something, you make it out of pieces of other things.",
    "bungle": "If you bungle, you do something incompletely or in a clumsy way.",
    "capable": "If someone or something is capable of something, they can do it.",
    "capacity": "The capacity of a container, room, etc. is how much it can hold.",
    "capital": "A capital is the most important city of a country. The government of the country is usually located there.",
    "capture": "If you capture a person or animal, you catch them and do not let them go free.",
    "care": "If you care for somebody, look after",
    "carry": "If you carry something, you lift it up and move it to another place.",
    "category": "A category is a group of people or things that are the same in some way.",
    "cause": "To cause something is to make it happen.",
    "cautiously": "If something is done cautiously, it is done in a cautious manner.",
    "challenge": "A challenge is something difficult that you want or have to do.",
    "change": "If you change something, you make it different than before.",
    "chapter": "A chapter is a main division of a book.",
    "character": "Character is the combination of personal qualities, such as being honest and hard-working, that make you a good person.",
    "check": "If you check something, you look at it to see if there is a problem, or something new or different.",
    "chill": "A chill is a feeling of coldness.",
    "circular": "If something is circular it has the shape of a circle.",
    "circumstance": "The circumstances surrounding an action or event includes all the information that helps you understand the action or event.",
    "city": "A city is large area where many people live and work, larger than a town.",
    "civil": "If someone is civil, they are polite but not friendly.",
    "class": "A class is a time for learning.",
    "clause": "A clause is a group of words that usually includes a subject and a predicate. In English, the subject usually comes before the predicate.",
    "clear": "If something is clear, it is easy to see or hear.",
    "climate": "The weather conditions of a place.",
    "cling": "If something clings to something else, it holds on tightly.",
    "close": "Close range/contact/ties etc. is near, not far.",
    "coast": "The coast is the area of land closest to the sea.",
    "coax": "If you coax someone, you gently persuade them to do something.",
    "collect": "If you collect some things, you bring them together as a group.",
    "colour": "To give something its colour.",
    "column": "A column is a support that is standing up and is built to support something, usually on a building.",
    "combine": "If you combine two or more things, you put them together.",
    "comment": "A comment is a short statement about something; usually it is an opinion.",
    "commission": "The official appointment of an officer in a nation's armed forces.",
    "commit": "If you commit something illegal or bad, you do it.",
    "common": "Found in large numbers or in a large quantity.",
    "communicate": "If you communicate an idea, you make someone else understand your idea, usually by using words.",
    "community": "A community is a group of people living in the same area and having a similar background or similar interests.",
    "companion": "A companion is somebody who you spend time with, usually because you enjoy being with them.",
    "compassion": "If you have compassion, you are aware of the pain of other people and want to help make it better.",
    "compensate": "If you compensate somebody, you give them something because they have lost something or done something for you.",
    "complete": "With everything included; entire, total.",
    "comply": "If you comply with something, you act accordingly to meet specific standards.",
    "component": "A component is one part that connects to other parts.",
    "compose": "If you compose something, then you create or write it.",
    "compound": "A compound is a material made of a number of other materials.",
    "compute": "If you compute an answer, you calculate it or find it, usually using mathematics.",
    "concept": "A concept is an idea.",
    "concern": "A concern is something that you think is a problem or needs attention.",
    "conclude": "When you conclude something, you come to the end of it and to finish it.",
    "conduct": "The way you conduct yourself is the way you act or treat others.",
    "confer": "If something is conferred on somebody, it is given to them, often officially.",
    "confess": "When you confess to doing something, you are saying that you did it.",
    "confident": "When someone is confident, the person is certain of something.",
    "confuse": "If you confuse some things, you mix them up in your mind.",
    "congratulate": "To congratulate somebody is to tell them that they did a good job.",
    "consent": "Consent is permission to do something.",
    "consequent": "happening as a result of sth.",
    "consider": "When you consider something you think carefully about it.",
    "considerable": "A considerable amount, time, degree, etc. is a fairly large or important one.",
    "consist": "If A consists of B, then B is the thing or things that, together, make A.",
    "constant": "If something is constant, it doesn't change over time.",
    "constitute": "If something is being constituted, it is being set up or established.",
    "constrain": "If you constrain a person, you force them to follow a certain way of doing things.",
    "construct": "To make, build, or form (something) by putting the parts together.",
    "consult": "If you consult with someone, you ask them their opinion or for advice.",
    "consume": "If you consume alcohol, food, etc., you eat or drink it.",
    "contain": "If you contain something, you stop it from getting out.",
    "content": "If someone is content, they are happy and satisfied.",
    "context": "Something's context is the situation that it happens in.",
    "contract": "A contract is a legal agreement to trade goods, services and/or property. It's usually written down.",
    "contrary": "A contrary view, sentence, etc. is opposite to other ones.",
    "contrast": "Contrasts are the differences you find when you compare something or someone.",
    "contribute": "If you contribute something, you make it available to other people.",
    "convene": "If people convene, they come together to meet or unite.",
    "convert": "If you convert something, you change it so that it has a different function or form.",
    "convince": "To make someone believe, or feel sure about something.",
    "cooperate": "If people cooperate, they help each other and work together towards the same goal.",
    "coordinate": "When you coordinate with someone, you work with him/her to finish an activity.",
    "core": "The core is the centre part of something.",
    "corporate": "Corporate finance, planning, management, etc. is related to business or a company.",
    "country": "A land that is controlled by a government.",
    "course": "A course is the path that something follows in space or in time.",
    "courteous": "A courteous person is someone who shows regard or thought for others.",
    "cover": "Something that is covering another thing is on top of (or over) the other thing in a way that stops people from seeing it.",
    "coward": "A coward is a person who does not have courage.",
    "crafty": "Being crafty means to be very clever and skilful, usually to trick, fool or deceive someone else.",
    "crave": "If you crave something, you have a strong desire for it.",
    "credit": "Credit is an agreement to buy something and pay later.",
    "crew": "A group of people working together to operate something such as a ship, factory, airplane, etc.",
    "criteria": "Criteria are a set of principles that you use to judge something or decide about something.",
    "cross": "If you cross something, you go from one side of it to the other side.",
    "culture": "A culture is a common history, set of beliefs, or way of life within a group of people.",
    "cut": "If you make something shorter or divide it in pieces, you cut it.",
    "data": "Data is information, such as facts, numbers, photographs, etc.",
    "date": "A date is a particular day in a month or year.",
    "debate": "A debate is an exchange of ideas looking at different sides of an issue.",
    "decide": "If you decide something, there were different things you could do, but you choose one.",
    "dedicate": "To show something to the public for the first time.",
    "deduce": "If someone deduces something, the person reaches a conclusion based on a logical process.",
    "deed": "A deed is an action that is done; sometimes it is brave and important",
    "deep": "A hole or body of water is deep if it goes down a long way.",
    "define": "If you define a word, you state exactly what the word means.",
    "demonstrate": "If you demonstrate something, you show that it is true or that it exists.",
    "dense": "If something is dense the pieces of it are close together, or there is a lot of material in a small space. Dense things are usually heavy and often hard.",
    "deposit": "If you deposit something, you put it down in a place.",
    "deprive": "To deprive is to keep something from someone.",
    "descend": "If you descend, you go down.",
    "design": "If you design something, you plan and show how it will look and work.",
    "desire": "A wish, a feeling of want.",
    "destructive": "If something (or someone) is destructive it destroys; it causes destruction.",
    "detect": "If you detect something, you use your senses to find or notice it.",
    "develop": "When you develop something, you create or make it better.",
    "diagram": "A diagram is a drawing, or sketch, to show how something, such as a machine, works.",
    "differ": "If things differ, they are not the same in some way.",
    "digest": "To break down food in the stomach and intestines",
    "dimension": "A dimension is a direction of measurement in space time, usually width, depth, and height.",
    "direct": "If something is direct, it is straight and as short as possible with nothing extra in between.",
    "disaster": "A disaster is a serious problem.",
    "discrete": "If two things are discrete, they are separate and distinct.",
    "distinct": "If two things are distinct, they are clearly different or separate.",
    "distract": "If you distract someone, you make them pay attention to something different than what they were paying attention to before.",
    "distribute": "When you distribute something, you divide it and give it out.",
    "diverse": "A diverse group of things is a group in which the things are very different from each other.",
    "document": "A document is a written record, often official.",
    "domain": "A domain is a field or area of knowledge or skill, or of where a rule is in force.",
    "domestic": "Domestic issues related to the issues inside one home.",
    "dominate": "If someone dominates something, they have sole, or nearly complete, control over it.",
    "don't": "The negative form of do; do not.",
    "door": "A piece of a wall that can be opened (leaving a hole in the wall to walk through) or closed (covering the hole). Some doors are on hinges; others slide.",
    "doze": "If you doze, you sleep lightly or briefly.",
    "draw": "When you draw, you use a pencil, pen, crayon, etc. to make a picture.",
    "dry": "If something is dry, it has no water or liquid on it.",
    "during": "If you do something during something else, you do it at the same time.",
    "early": "If something is early, it is sooner than expected.",
    "earth": "A planet, especially one like Earth.",
    "ease": "To free or lessen (something) from pain, worry, agitation, etc.",
    "east": "The east is a place that is closer to where the sun rises than another place.",
    "economy": "The economy is the use of the resources of a community or system.",
    "element": "An element is one part of something bigger, such as a plan, an engine, or a business.",
    "emerge": "If you emerge, you come out of something.",
    "emphasis": "Emphasis is the giving of particular attention or importance to something.",
    "enable": "If you enable something or someone, you make make it able to do something or you help it.",
    "end": "The last one of a group. Or, the last part of a thing, the place where it stops.",
    "energy": "Energy is the ability to do work: move, give off heat, give off light, etc.",
    "enforce": "To enforce means to make sure that something will be made into effect and followed.",
    "enough": "the needed number or amount",
    "ensure": "If you ensure that something is correct or that it happens, you check it and fix any problems.",
    "entertain": "You entertain a person by keeping that person interested in what you are doing.",
    "entire": "The entire thing is the whole thing, every part of it; used for emphasis.",
    "entity": "An entity is a whole thing, independent from other things, often an institution or something alive.",
    "entrance": "An entrance is a way into somewhere, for example a door or a gate.",
    "envy": "A feeling of wanting something that someone else has.",
    "equate": "If you equate two things, you consider them to be equal.",
    "equivalent": "If two things are equivalent, they are of equal value or acceptability.",
    "erupt": "If something erupts, it violently spits out something.",
    "escalate": "If you escalate something, you increase its intensity.",
    "essential": "If something is essential, it is very important.",
    "establish": "If you establish something, you start it with the idea that it will last for a long time.",
    "estate": "Someone's estate is everything they own, or everything they leave when they die.",
    "estimate": "If you estimate the number, size, value, amount, cost, etc. of something, you guess based on incomplete information.",
    "ethnic": "An ethnic group is a group related by race, culture, and/or nationality.",
    "evade": "If you evade something, then you try to avoid it or keep away from it.",
    "evaluate": "If you evaluate someone or something, you judge it.",
    "even": "If a number is even, it can be divided into 2 equal parts.",
    "ever": "If I ask you if you have ever been to France, I am asking if you have been to France at any time in your life.",
    "every": "all the people, things, times, etc.",
    "evident": "If something is evident it is very easy to realize or understand.",
    "evolve": "If something evolves, it, or things of its kind, change slowly over a long time or from generation to generation.",
    "examine": "If you examine something, you look at it carefully.",
    "example": "An example is a model of what something else of the same type should be like.",
    "exasperate": "If you exasperate a person, you irritate or frustrate them severely.",
    "exceed": "If you exceed something, you go beyond (farther than) the limits, beyond the regular level or beyond what is allowed.",
    "exclude": "If you exclude someone or something, you keep them out.",
    "exert": "If you exert yourself when doing something, you use a lot of strength to do it.",
    "exhibit": "You exhibit something when you show it to others.",
    "expand": "If something expands, it becomes bigger.",
    "explore": "If you explore a possibility, plan, idea, etc. you think about it carefully.",
    "export": "If you export something, you send it out of the country, usually for business purposes.",
    "extend": "If you extend something, you make it longer.",
    "external": "Something that is external is not on the inside.",
    "extraordinary": "Something that is above the everyday, above the ordinary, more than ordinary, spectacular.",
    "face": "A face is the front part of the head.",
    "facilitate": "If X facilitates Y, X makes Y easier.",
    "fact": "A fact is a piece of information that is true.",
    "factor": "A factor is one of a number of things that causes a result.",
    "family": "A family is a group of people with a blood or marriage relation.",
    "far": "a long distance away",
    "father": "The father of a person is the man who is one of that person's parents.",
    "feature": "A feature is a special or noticeable part of something.",
    "feel": "If you feel that something is the case, you have a strong idea in your mind that it is the case.",
    "feet": "The plural form of foot; more than one (kind of) foot.",
    "few": "not many",
    "fierce": "If something or someone is fierce, then they are violent or aggressive.",
    "fill": "If you fill something, you put something in it until there is no space left.",
    "final": "The final thing is the last one.",
    "finance": "Finance is activities related to banking and money, especially by government.",
    "fire": "A chemical reaction that makes heat and flames or smoldering.",
    "fish": "A fish is an animal that lives in the water and has scales and gills.",
    "flexible": "When something is flexible, it can bend.",
    "focus": "If you focus on something, you pay special attention to it.",
    "follow": "If the first thing occurs after the second, thing the first thing follows a second thing.",
    "food": "Food is what people and animals eat for nutrition or pleasure when they are hungry.",
    "foot": "The lowest part of the leg, below the ankle; the part of the body used to stand on.",
    "force": "A force is the act of a thing pushing on another thing, or how strongly it pushes.",
    "formula": "A formula is a way to do something or solve a problem that does not change much.",
    "fragile": "If something is fragile then it is delicate and it will break easily.",
    "frail": "When a person is frail, they are weak and easy to break down physically and mentally.",
    "framework": "A framework is basic ideas and organisation that you can build an argument, a book, a society, etc. around.",
    "frantic": "If someone is frantic, they are very worried or upset, often because of fear or stress.",
    "free": "If something is free, it does not cost money to buy.",
    "frequent": "An event is frequent if it happens many times in a short time.",
    "friend": "Two people are friends of each other if they like being together and they like helping each other, but are not related.",
    "full": "A container is full of things if there are many of the things in the container and no more can go in.",
    "function": "Something or someone's function is its purpose or its job.",
    "fund": "A fund is an amount of money kept for a specific purpose.",
    "fundamental": "If something is fundamental, it is basic and important.",
    "furious": "If you are furious, you are very, very angry.",
    "game": "A game is something that people do to have fun.",
    "gasp": "To gasp is the act of drawing in the breath suddenly, as if surprised.",
    "generate": "If you generate something, you create it.",
    "generation": "A generation is the average time between one when group of people were born and when their children were born, roughly 20-30 years.",
    "get": "Receive or obtain.",
    "gigantic": "Something that, when it is described, is even bigger than the word \"large\". Something that is very, very large.",
    "give": "If you give something to someone else, you had the thing and you let the other person have it. Maybe you use your hands to put the thing in the other person's hands. Usually after that, the thing is the other person's thing.",
    "glide": "To glide is to move without making an effort.",
    "globe": "The globe is the Earth.",
    "goal": "A goal is something you want to do or be able to do.",
    "gold": "Gold is a metal, which can be used to make coins and rings. It costs a lot of money to buy. Its symbol is Au on the periodic table and its atomic number is 79.",
    "good": "When you are good, you do the right things. That is, you do things that are kind or helpful. You do not do things that hurt people or are not honest.",
    "grant": "If you grant something to something, you give it to them, usually formally.",
    "grasp": "If you grasp something, you hold it tightly in a hand or hands.",
    "great": "A great person or object is very good.",
    "ground": "Ground is earth or soil.",
    "group": "When more than 2 things or people are together, they make a group.",
    "grow": "When things grow they get bigger or change in other ways over time.",
    "habit": "A habit is something that you do regularly.",
    "habitat": "A habitat is a natural place that a plant or an animal lives in.",
    "half": "A half is one part of a game that is divided into two parts.",
    "hand": "Your hands are the parts of your body at the end of your arms. A hand has four fingers and a thumb.",
    "happen": "if something happens, it starts or changes without a plan.",
    "hard": "If something is hard, it is not soft.",
    "hazy": "If it is a hazy day, the sky is not clear and covered by a haze.",
    "head": "The head is the highest and most important part of the body.",
    "hear": "If you hear a sound, you notice it with your ear.",
    "hearty": "Hearty means to have good health and vigor.",
    "help": "If you help another person do something, you do things to make it easier for them to do the thing, or you do part of it for them.",
    "hence": "for this reason",
    "here": "(in, at or to) this place",
    "high": "If something is high, it is a long way up.",
    "home": "Where a person lives. Usually, where people keep their things that they are not carrying, and where they sleep.",
    "homonym": "Homonyms are two words that both sound and are spelled the same as each other.",
    "horse": "A horse is a hoofed mammal. It walks on four (4) legs. People often ride on horses.",
    "house": "A house is a building that one family lives in.",
    "humble": "If you are humble, you are aware of your own weaknesses and do not want or accept recognition of your good qualities or successes.",
    "idea": "An idea is a concept or a thought.",
    "identical": "If two ore more things are identical, they are exactly the same.",
    "ignorance": "Ignorance is a lack of knowledge.",
    "illuminate": "If something is illuminated, it shines light on something.",
    "illustrate": "If you illustrate something, you draw a picture of it, or you explain it.",
    "image": "An image is something you can see or imagine that looks like the real thing.",
    "immense": "If something is immense, then it is very large or big.",
    "immigrate": "If you immigrate to a country, you move to there to live.",
    "impact": "The impact is the effect of an act, statement, change, etc.",
    "implement": "If you implement a plan, you put it into action; you do it.",
    "implicate": "If x is implicated in y, x is connected to y and may be its cause.",
    "imply": "If you imply something, you mean it, but you don't say it directly.",
    "impose": "If you impose something on someone, you force it on them, even if they don't want it.",
    "impressive": "If something is impressive, it makes a positive impression or is able to impress someone.",
    "inch": "A unit of length that is equal to 2.54 centimetres; there are 12 inches in a foot.",
    "incidence": "The incidence of something is how often it happens.",
    "income": "Income is the money that you get from working.",
    "increase": "To grow; to become bigger.",
    "independent": "If something or someone is independent, they are free; they are not dependent on anything.",
    "indicate": "If someone indicates something, they point it out or they point to it; they bring your attention to something.",
    "individual": "An individual is a single person, looked at separately from others.",
    "inhibit": "To inhibit is to stop something happening, or to make it happen less.",
    "initial": "The initial period, stages, etc. come near the beginning.",
    "injure": "Injure means to hurt someone or an animal; causing harm to a person or an animal.",
    "inspire": "If something inspires you, it gives you ideas, or it makes you want to create.",
    "instance": "An instance of something is a time or situation when it happens.",
    "instant": "Instant x is x that is ready, or happens, very quickly (in an instant).",
    "institute": "An institute is an organisation such as a school or hospital that does teaching or research.",
    "integrate": "If you integrate x into y, you combine them together to form one whole.",
    "intense": "Something that is intense has a very strong action or effect.",
    "interact": "If you interact with someone or something, you communicate or work with someone or something else.",
    "intercept": "If you intercept something, you stop or divert something that is in progress or motion.",
    "interest": "An interest is when someone wants to know more about someone or something or likes someone or something or likes to do something.",
    "internal": "within or inside",
    "interpret": "If you interpret something, you understand a particular meaning in it, and may explain that meaning to others.",
    "invest": "If you invest in something, you spend time or money to make it better.",
    "investigate": "If you investigate a problem, you get information about it and you think carefully about the information, usually to find an answer.",
    "invisible": "Something is invisible when we can not see it.",
    "involve": "If an activity involves something, then that thing is used in or is part of the activity.",
    "island": "An island is a piece of ground that is completely surrounded by water.",
    "issue": "An issue is a particular topic or subject, often one that people are discussing and/or is a problem.",
    "jagged": "When something is jagged, it is unevenly cut.",
    "journal": "A journal is a record of what is happening, usually written regularly (e.g., daily, weekly, monthly, etc.), often scientific.",
    "journey": "A journey is a long trip.",
    "justify": "If you justify something that people think is bad, you explain why it was good or why it had to happen that way.",
    "keep": "When you keep something for someone, you make something safe.",
    "kind": "Good for another person.",
    "label": "A label is a small sign, usually on something, to tell you about it.",
    "labor": "If you labor, you work hard.",
    "lack": "If there is a lack of something, there is not enough of it or it doesn't exist at all.",
    "land": "Land is the part of the Earth that is not covered with water",
    "language": "A language is all the words used by a group of people, and grammar (the rules for making them into sentences). People who speak the same language can understand each other; people speaking different languages cannot understand each other.",
    "large": "Big; of great size; broad, tall, wide, long, or fat.",
    "last": "Happening or coming after all other similar things or people.",
    "late": "An event is late if it happens after a specified time.",
    "laugh": "Someone laughs when they make a sound with their mouth because they think something is funny. It can sound like \"ha ha\", \"ho ho\", \"hee hee\", etc.",
    "launch": "If you launch something, you start it or get it going.",
    "layer": "A layer is a covering material or substance.",
    "leave": "When you leave a place, you go away from it.",
    "left": "The left side.",
    "legal": "If an activity is legal it does not break any laws.",
    "legislate": "If you legislate, you create or change a law.",
    "less": "A smaller amount or degree.",
    "let": "When you let someone do something, you allow them to do it.",
    "letter": "A letter is a written message or note.",
    "liberal": "If something is liberal, it allows for change, flexibility, and free thought.",
    "license": "Officially authorize.",
    "life": "Life is the time when people, animals or plants grow and exist before they die. Your life is the time that you live.",
    "light": "The energy that our eyes sense is light.",
    "limb": "A limb is either a leg or an arm.",
    "limit": "The limit is the edge of how far something can go. It can go up to the limit but no farther.",
    "limp": "If someone limps, they walk with a lamely gait.",
    "line": "A line is a mark that is long, straight and very thin.",
    "list": "A list is a group of related words, often in some order, often to help you remember something.",
    "little": "If something is little, its size is not big.",
    "live": "To be alive; to have life.",
    "logic": "Logic is a system of careful step by step thought or argument that tries to explain truth.",
    "lot": "To a large degree.",
    "low": "If something is low, it (or its top) is close to the ground.",
    "loyal": "To be loyal is to be true to someone; to always tell the truth to someone.",
    "main": "The main thing is the most important or biggest one.",
    "maintain": "If you maintain something, you keep it at the same level.",
    "major": "A major change, problem, event, etc. is a big and important one.",
    "man": "A man is a male human.",
    "manufacture": "If you manufacture something, you make it, usually in a factory.",
    "margin": "A margin is the space on the sides of a page where there is no writing.",
    "mark": "A mark is a single line left by a pen or pencil, or any small bit of color that got onto something.",
    "massive": "Very big; large; too big.",
    "master": "If a person masters something, they become very good at it; they are skilled at it.",
    "mature": "If something is mature, it is fully developed.",
    "maximise": "If you maximise something, you make it as large as possible.",
    "measure": "If you measure something, you calculate its size, mass, temperature, etc. using units like centimetres, kilograms, degrees, etc.",
    "mechanism": "A mechanism is the way something works",
    "medical": "About physical health and medicine.",
    "men": "The plural form of man; more than one (kind of) man.",
    "mental": "Mental health, processes etc. is related to the mind and thinking.",
    "method": "If you use a method to achieve a goal, then you use a planned process.",
    "migrate": "If you migrate, you move from one place to another. Usually for something better.",
    "mind": "Someone's mind is the part of them that thinks.",
    "minor": "A minor change, problem, injury, etc. is not very important.",
    "minute": "A minute is a short time equal to sixty seconds. There are sixty minutes in one hour.",
    "mischief": "Mischief is the intention to cause minor trouble or the trouble caused.",
    "miss": "If you miss something, you don't hit it.",
    "mistrust": "If you mistrust someone, you think they are not honest or trustworthy.",
    "mock": "To copy someone's actions in a bad way.",
    "modify": "If you modify something, you change it, often only in small ways, and often because you want to use it in a different situation.",
    "moon": "The moon is the shining white and grey object in the sky at night. It appears to change shape from round (a full moon) to a crescent and back again. It's like a small planet that goes around the Earth.",
    "morning": "Period between sunrise to midday.",
    "mother": "A mother is the woman who is one of a person or animal's parents.",
    "mountain": "A natural rise of the Earth's surface having considerable mass",
    "move": "If you move, you go from one place to another.",
    "much": "a lot of; a large amount of; a high degree",
    "must": "Must is usually used to tell someone they have no choice about doing something because it is important or because of a rule or law.",
    "mystify": "If you mystify a person, you confuse them thoroughly.",
    "nation": "A nation is a country or a political entity.",
    "near": "Close.",
    "need": "If you need something, you want it and must have it.",
    "negate": "If x negates y, x makes y lose the effect that it had.",
    "network": "A network is a group of connections between a number of points.",
    "never": "If something never happens, it does not happen at any time.",
    "new": "If something is new, it is not old.",
    "next": "The next thing is the one after this one.",
    "night": "Period between dusk to dawn.",
    "noble": "Noble qualities are those admired by others.",
    "north": "North is the direction towards the top of the Earth, opposite to south; If you are looking north, the sun sets on your left.",
    "nothing": "Not anything. Without any things.",
    "notion": "A notion is an idea about something.",
    "numeral": "A numeral is a symbol or word that represents a number, such as the Arabic numerals 1, 2, 3 and the Roman numerals I, V, X, L.",
    "numerous": "If something is numerous, it is in large amount.",
    "nursery": "A nursery is place where young plants are grown before planting (putting in the ground) outdoors.",
    "oasis": "A spring in a desert, where there is water and plant growth around the water.",
    "object": "An object is a thing that you can touch, but it is not alive.",
    "objective": "If something is objective, it is based on facts and things we can see and touch without using people's feelings.",
    "observe": "If you observe something, you watch it carefully.",
    "obsolete": "If something is not used anymore, or if something newer replaced it, it is obsolete.",
    "obtain": "If you obtain something, you get it.",
    "obvious": "If something is obvious, it is easy to see it, think of it, or understand it.",
    "occasion": "An occasion is a particular time.",
    "occupy": "If something occupies a space, it is there, lives there, or belongs there.",
    "occur": "If something occurs, it happens.",
    "off": "Away from somewhere or some time.",
    "often": "When something happens often, that means that it happens many times and frequently.",
    "old": "If someone or something is old, they are not young; they have been in existence for a long time.",
    "once": "one time",
    "open": "Having a hole or opening, not closed.",
    "opposite": "If two things are opposite, they are the same kind but completely different from each other.",
    "option": "An option is a choice.",
    "orchard": "An orchard is a plantation of fruit such as apples, plums, and peaches.",
    "ordeal": "An ordeal is a very unpleasant experience.",
    "order": "Order is when things are where they should be.",
    "orient": "When you orient something, you point it in a certain direction.",
    "origin": "The origin of something is the place where it comes from.",
    "other": "different",
    "outcome": "An outcome is the result of a situation or action.",
    "output": "Output is what is produced by a worker, machine, computer, etc.",
    "outstanding": "If something is outstanding, it stands out from the others, usually in a good way.",
    "overall": "An overall effect, strategy, picture, etc., is one that covers everything but may not go into detail.",
    "overthrow": "If you overthrow someone, you remove them from power with force.",
    "own": "If you own something it belongs to you, it is yours.",
    "page": "A page is one side of a sheet of paper in a book, newspaper, etc.",
    "parallel": "When a line is parallel to another line, the two lines do not meet and they are the same distance from each other at every point.",
    "part": "A part of something is one piece of it or a small amount of it.",
    "participate": "If you participate in something, you join in it; you take part in something.",
    "partner": "Partners are people, usually two, who are together for a particular purpose, such as for business, sports, or a romantic relationship.",
    "pass": "If you pass something, it was ahead of you and you move so that it is now behind you.",
    "passage": "A passage is a short section from a book or other writing.",
    "pastime": "A pastime is an activity that you do to use up time.",
    "pasture": "land covered with grass. there are cattle or sheep.",
    "pause": "A pause is a short time for stopping a work and doing some other work.",
    "peculiar": "When something is peculiar, it is out of the ordinary or is unusual.",
    "pedestrian": "A person who is walking or traveling by foot.",
    "peer": "A peer is someone of the same level as you.",
    "perceive": "If you perceive something, you notice it through one of your senses (you see it, touch it, smell it, hear it, or taste it); to be aware of something.",
    "percent": "You use percent show the number of parts out of a hundred. The symbol for percent is %.",
    "perform": "When you perform something, you do it.",
    "period": "A period is a length of time.",
    "perish": "To perish means to die (stop living).",
    "perspective": "A perspective is a way of looking at or thinking about something.",
    "phase": "A phase is stage in a process.",
    "philosophy": "Philosophy is the study of the nature of existence and truth: how things are and how they should be.",
    "physical": "A physical thing or activity is related to the body, or something you can touch.",
    "picture": "A picture is a still or moving image on a screen.",
    "piece": "A piece is a part of something that can be or has been separated from it.",
    "place": "A place is an area of land.",
    "plain": "If something is plain, it is simple and undecorated.",
    "plane": "A plane is a vehicle with wings that flies.",
    "plant": "A plant is something that lives and grows in one place. Plants usually have green leaves and roots. Flowers and trees are plants. Plants and animals are the main kinds of life.",
    "plead": "If you plead for something, you ask for it in a strong and emotional way.",
    "plunge": "If you plunge into something, you jump or dive quickly into it.",
    "point": "A point is the sharp end of a knife or other sharp thing.",
    "policy": "A policy is an official rule or idea that explain how to act in certain situations.",
    "portable": "If something is portable, it can be moved or carried.",
    "positive": "If something is positive, it is good, happy, or wanted.",
    "possess": "To have or to own",
    "possible": "If something is possible, it is able to be done; doable; not impossible.",
    "potential": "If something has or shows potential, they will likely be very good in the future.",
    "practice": "If you practice something, you do it again and again to improve your ability.",
    "precise": "If something is precise it is correct and exact.",
    "predict": "If you predict something, you say that it will happen before anyone observes it.",
    "prefer": "If you prefer something, you like it more than another thing.",
    "prejudice": "a belief, usually negative, that you have about something, before you know that it is actually right",
    "prepare": "When we prepare something, we get it ready.",
    "preserve": "To preserve is to keep something from decay or loss.",
    "press": "If you press something, you push it against something.",
    "presume": "If you presume something, you believe that it is true without evidence.",
    "prevent": "When you prevent something, you stop it from happening.",
    "previous": "If something happened at a previous time, it happened before a particular time.",
    "price": "The amount of money you need to pay to buy something.",
    "primary": "first.",
    "prime": "If something is prime, it is best, most important, most suitable, or in some way number one.",
    "principal": "The principal thing is the main or most important one.",
    "prior": "occurring before",
    "problem": "A problem is something that is difficult to do, understand, or believe.",
    "proceed": "When you proceed, you go forward with something.",
    "process": "A process is a series of steps that you take for a particular purpose.",
    "produce": "Someone or something produces something when they make it or create it or make it come out.",
    "product": "A product is a chemical substance that is made as a result of a chemical reaction.",
    "professional": "If someone is professional, they do their job seriously and with much skill.",
    "project": "A project is a complex job or assignment, often involving research or construction.",
    "promote": "If you promote someone or something, you help it to get bigger, higher, or more popular.",
    "proportion": "The proportion is the relationship in size between one part and another.",
    "protagonist": "In a literary work or drama, the protagonist is the main character.",
    "provide": "When you provide, you give means of support.",
    "psychology": "The study of the mind and behaviour.",
    "publish": "If you publish a book, an article, a song, etc. you make it available for other people to buy, read, listen to, etc.",
    "purchase": "If you purchase something, you buy it.",
    "pursue": "If you pursue someone or something, you try to reach, catch or get it.",
    "put": "When you put a thing someplace, you move a thing to a place.",
    "queasy": "If you feel queasy, you are experiencing nausea.",
    "question": "Something someone says to have someone else say an answer.",
    "range": "The range is area between an upper and lower limit.",
    "ratio": "A ratio is the comparison in size or number between two things. It is written x:y and read x to y. It is the same as the fraction x/y.",
    "react": "If you react to a medicine or other substance, something happens in your body because of it.",
    "read": "Someone is reading when they are looking at a book or other writing and understanding what it says.",
    "ready": "Prepared.",
    "real": "A thing that is true is real.",
    "recall": "If you recall something, you think about something you learned or experienced in the past.",
    "recent": "Something that is recent has happened a short while ago.",
    "recognise": "If you recognise something, you realise what it is.",
    "reduce": "If something is reduced, it has been brought down or made smaller.",
    "regime": "A regime is a plan or system.",
    "region": "A region is an area of land or of the body.",
    "regulate": "If you regulate something, you control it by making laws and rules.",
    "release": "If someone releases something, they let go of it; they stop holding it and set it free (let it be free).",
    "relevant": "If something is relevant, it is connected to a topic in a meaningful way.",
    "rely": "When someone relies on another person, they need the person to do something, and they trust the person and feel certain that the person will do it.",
    "remark": "If you remark upon something, you say what you noticed or think about it.",
    "remember": "When you remember something, you put it in your mind so you can think of it later.",
    "represent": "To represent is to stand in the place of; to act the part of (another).",
    "request": "A request the act of asking for something (sometimes in a formal way).",
    "require": "If you require something, you need it.",
    "resemble": "If two things resemble each other, it means they are similar or look like one another.",
    "reside": "If something or someone resides somewhere, it lives there or is located there.",
    "resident": "A resident is somebody who lives in a particular area.",
    "resist": "If you resist something, you work, push, fight, etc. against it.",
    "resolve": "To resolve means to make a serious decision to do something.",
    "resource": "A resource is something that is available and useful.",
    "respect": "When someone respects another person that means they think the other person is worthy, responsible, strong or other good qualities.",
    "respond": "If you respond to something or someone, you do something in reaction to it.",
    "response": "A response is some words or actions that happen as a reaction to something else.",
    "responsible": "If you are responsible, you make good decisions and make sure that important things get done.",
    "restrict": "If you restrict something, you limit it.",
    "retain": "If you retain something, you keep it.",
    "retire": "If you retire, you stop working, usually because of your age.",
    "retrieve": "If you retrieve something, you go and get it back.",
    "reveal": "If you reveal something, it was hidden and you show it or make it known.",
    "revenue": "Revenue is the money that a business receives for doing business, and government receives from taxes.",
    "reverse": "If you reverse something, you make it act or move opposite to before (in the other direction).",
    "revert": "When you revert, you are undoing an action.",
    "right": "When something is right, it is correct.",
    "rigorous": "To be rigorous someone needs to be very strict, exact and not change the rules.",
    "risk": "A risk is the chance of something bad happening.",
    "rock": "A hard substance that forms naturally in the Earth's surface.",
    "room": "A room is a place which is part of a building. Someone is able to see other people who are in the same room.",
    "round": "Something is round if it's like a circle or like part of a circle. It is curved, not straight.",
    "route": "A route is the way someone goes from one place to another place.",
    "same": "Two things are the same if the two things have one size, and one shape, and one color, etc.",
    "saunter": "If you saunter, you walk in a slow and relaxed way..",
    "save": "If you save something, you keep it; you do not give it or toss it away.",
    "say": "When you say something, you share it in words.",
    "scatter": "To scatter means to go in different directions; separate.",
    "schedule": "A schedule is a plan of things that are happening and the times when they happen.",
    "scheme": "A scheme is a plan, sometimes a bad or dishonest one.",
    "second": "The second thing is the one that is number two (2) in order.",
    "section": "A section of a thing or place is a part of it.",
    "sector": "A sector is a part or division of an area, especially part of the economy.",
    "secure": "When something is secure, it is firmly held in place and probably will not fall.",
    "seem": "The way something seems to be is the way you think it is when you look at it, hear about it, think about it, etc.",
    "seldom": "If you seldom do something, you almost never do it.",
    "senseless": "If something is senseless, it does not have a meaning or purpose.",
    "sentence": "In grammar, a sentence is a group of words that follow normal grammar rules, and that, in writing, begins with a capital letter and ends with a period '.', question mark '?', or exclamation mark '!'. Usually a sentence has a subject, verb, and object.",
    "sequence": "A sequence is a set of things in a specific order.",
    "series": "A TV or Radio series is a number of programs usually with the same setting and characters.",
    "set": "If you set something somewhere, you put something into a place.",
    "sever": "If you sever something, you cut through or separate it completely.",
    "severe": "Someone who is severe gets angry easily or frequently punishes people; they are harsh or strict.",
    "shabby": "If a person's clothing is shabby, it is torn or worn.",
    "shallow": "If you are shallow, you only care about things that are obvious to you, and you never think deeply about the world around you.",
    "shape": "The shape of a thing is its external form.",
    "shift": "If something shifts, it moves.",
    "ship": "A ship is a large boat.",
    "short": "If something is short then there is a small distance from the bottom to the top. The opposite is tall.",
    "should": "You use should to say that it is a good idea to do something.",
    "show": "When you show something, you make it easy for people to see it.",
    "significant": "If something is significant, it is important, or large, enough to pay attention to or to believe.",
    "similar": "If two things are similar, they are almost the same, or the same in many, but not all, ways.",
    "since": "From a particular time in the past until now or until a later time in the past.",
    "size": "How big or small a thing is.",
    "sluggish": "A sluggish person is someone who is lazy.",
    "small": "A small person or thing is not big. It doesn't have much size.",
    "snow": "Snow is precipitation (falling water) that is white and frozen.",
    "soar": "To fly high with little or no effort.",
    "solar": "If something is solar, it is of or related to the sun.",
    "solitary": "If a person lives in 'solitary, they live alone without anyone accompanying them.",
    "solo": "If something is done solo, you do it without a companion.",
    "song": "A song is some music with words in verse.",
    "soon": "If something is soon, it is shortly after another time, often shortly after the time of speaking.",
    "soothe": "If you soothe a person, you relieve or calm them.",
    "source": "The source of some material, an idea, a product, etc. is the place it came from originally.",
    "south": "The direction opposite to north. For a person looking at the setting sun, the south is on their left hand.",
    "special": "If something is special, it is not usual; it is different or important in some way.",
    "specific": "If you talk about a specific idea, person, group, or thing, you mean that it is different from or more interesting than other things like it; you might also mean that you know exactly which one you are talking about.",
    "specify": "If you specify something, you say exactly which one or how to do something.",
    "spell": "To say or write all the letters that make up a word, in the right order.",
    "spoil": "If you spoil something, you ruin it, you make it no good.",
    "stable": "If something is stable, it is unlikely to move or change.",
    "stand": "When you stand, your body is at rest and supported only by your feet.",
    "start": "To begin; to do something for the first time.",
    "starve": "When you starve, you die from not having enough food.",
    "state": "A state is a condition or a situation.",
    "stationary": "When an object is stationary, it is not moving.",
    "statistic": "Statistics are numbers about information.",
    "stay": "When you stay somewhere, you do not move from there.",
    "steer": "To steer is use a rudder, wheel, or paddle to decide which way something will travel.",
    "still": "If something is still, it is not moving and resting in one place.",
    "stop": "If you stop, you come to the end of the time when one is doing something. You start doing a different thing or start doing nothing.",
    "story": "A story is a piece of text that tells someone who reads it about a real or fictional (made up) event.",
    "street": "A road in a city with buildings on the sides and places where people can walk.",
    "stress": "Stress is emotional pressure that makes you worry because things are not going well.",
    "strive": "If you strive, you struggle or try something very hard.",
    "strong": "Having big muscles; physically powerful.",
    "structure": "The structure of something is the way that it is put together.",
    "study": "If you study something, you make an effort to learn it.",
    "style": "A style is a specific look, design, or way of dressing or acting.",
    "subsequent": "happening after sth else.",
    "substitute": "A substitute is a person on standby for a sport team or school teacher.",
    "such": "Such a person or thing is that same kind that was mentioned before.",
    "sufficient": "If something is sufficient, it means there is enough or that it is good enough.",
    "suffix": "A suffix is an affix that is added to the end of a word. In English this can change the meaning. Also, it can be required by grammar but not change the meaning; this could be to change the tense, the number, or for other reasons.",
    "suffocate": "To suffocate is the action of dying from lack of air.",
    "suitable": "Something suitable is right for a particular purpose.",
    "summary": "A summary is a short explanation of a longer idea, article, story, etc.",
    "summit": "The summit of a mountain is located at the highest point of it.",
    "superior": "If x is superior to y, x is better than y.",
    "supplement": "A supplement is an extra that is added to something.",
    "sure": "When you are sure about something, you are certain.",
    "surface": "The surface of an object is the outside of the thing.",
    "survey": "If you survey people about their thoughts or personal information, you ask a large number of people in a formal way, often using a questionnaire.",
    "suspend": "If you suspend something, you stop it for a time.",
    "sustain": "If something is sustained, it is maintained.",
    "swarm": "A swarm is a group of many insects, especially flying insects like bees, wasps or flies.",
    "swift": "If something is swift, it is fast.",
    "symbol": "A symbol is a person or object that represents a group or idea.",
    "synonym": "A synonym is a word with the same meaning as another word.",
    "tail": "A tail is a long, thin part on the back end of an animal.",
    "take": "If you take something or someone, you bring them from one place to another.",
    "talk": "to speak; any sound from a person's mouth.",
    "talon": "A talon is a big, sharp claw of an animal, usually found on birds of prey, such as the eagle, hawk, falcon, owl, or buzzard.",
    "taunt": "When you taunt someone, you make sarcastic remarks about them in the hope of making them angry.",
    "technical": "Technical problems, writing, or skills, are related to special knowledge that most people don't have.",
    "technique": "A technique is a specialized and skillful way of doing something.",
    "technology": "Technology is the tools, equipment, and activities that come from scientific knowledge.",
    "tell": "When you tell something to someone, you speak to the person about some fact or idea.",
    "terror": "Very strong or intense fear.",
    "test": "A test is something someone does to see if something works.",
    "theory": "A theory is an idea that tries to explain an observation.",
    "think": "You use think when you have words or ideas in your mind without saying them out loud.",
    "those": "The plural form of that; more than one (kind of) that.",
    "thought": "When you have a thought, you have an idea or concept in your mind.",
    "thousand": "The number 1,000.",
    "three": "The number 3.",
    "together": "If you say that someone is together, you mean he or she is well organized and focused.",
    "tour": "A tour is a planned walk, bus trip, or flight, to look at a particular place.",
    "tradition": "A tradition is something that has been done in the same way for a long time.",
    "tragic": "When an event is tragic, it is causing a lot of pain and suffering for those involved in that event. We would call such event a tragedy as well.",
    "transfer": "If you transfer (something), you move (it) to a different place.",
    "transit": "Transit refers to the movement of goods or people from one place to another.",
    "travel": "When you travel, you visit some place; you go on a journey or adventure.",
    "tree": "A tree is a tall plant of wood.",
    "trend": "A trend is a general movement or change in one direction.",
    "triumph": "A triumph is a great success.",
    "true": "If something is true, it is correct or real, not imagined or made up.",
    "turn": "To face a different direction",
    "typical": "If something is typical, it is normal, and not special. It's what you would expect.",
    "under": "In the same place as another thing, but lower.",
    "undertake": "If you undertake something, you take responsibility for doing it and you start to do it.",
    "until": "If something is true until x, it is true for some time before x and then is not true.",
    "us": "You use us to talk or write about yourself and other people together with you.",
    "usual": "something that is usual happens often",
    "utilise": "When you utilise something, you make use of it.",
    "valiant": "A valiant person is someone who possesses or shows courage.",
    "valid": "If something is valid, it is correct, appropriate, and acceptable.",
    "value": "Something's value is how good or important it is; how much money someone will exchange a thing for; an amount of money.",
    "variety": "A variety of things is a group of things that are not all the same.",
    "vary": "If something varies, it is not always the same.",
    "vast": "If something is vast, it is very, very big.",
    "venture": "A venture is an undertaking.",
    "version": "A version is something that exists in different forms.",
    "very": "Much; quite. Using very makes the adjective or adverb stronger.",
    "visible": "If something is visible, it can be seen.",
    "vision": "Vision is being able to see with your eyes.",
    "vivid": "When something is vivid, it is very bright or deep in color.",
    "volume": "The volume of sound or music is how loud it is.",
    "volunteer": "To do something voluntarily--to do it without being offered something in exchange",
    "wander": "When you wander around, you walk or move slowly around without a purpose.",
    "want": "If you want to do something, you think you would be happier if you did it.",
    "watch": "To watch is to look for a long time or to look at somebody doing something.",
    "weary": "If a person is weary, they are very tired of fatigued.",
    "weight": "The weight of something is how heavy it is.",
    "welfare": "Someone's welfare is their health, safety, and other things the make them happy.",
    "well": "In a good way.",
    "wheel": "A wheel is a round thing (circle) on a cart or carriage or train or other machine that moves. A cart has four wheels that touch the road and turn.",
    "when": "at what time; on what occasion",
    "where": "(In or to) what place or situation.",
    "while": "If x happens while y happens, they happen at the same time.",
    "whole": "The whole of something means the entire part of it.",
    "why": "Used to ask the reason for something.",
    "wind": "Wind is the moving air.",
    "withdraw": "If you withdraw (something) from somewhere, you take (it) out.",
    "wonder": "If you wonder about something, you think about it because you want to know more about it.",
    "wood": "Wood is what trees are made of. People use wood to build things like houses and furniture.",
    "work": "Your work is your job.",
    "world": "The Earth.",
    "year": "A measure of the time taken for the earth to circle the sun - any 12 month period",
    "young": "If you are young, you have not lived a long time.",
    "your": "Your things are things which belong to you.",
};
