// Definitions generated from Simple English Wiktionary via Kaikki on 2026-05-25.
// The source data is derived from CC-BY-SA and GFDL licensed Wiktionary content.
// Words without a confident Simple English Wiktionary match keep their local fallback in vocab.ts.
export const SIMPLE_WIKTIONARY_DEFINITIONS: Record<string, string> = {
    "abandon": "To go away from something with no plan to return.",
    "above": "Higher than or earlier than something else.",
    "abrupt": "Sudden or unexpected.",
    "abundant": "Existing in large amounts.",
    "accelerate": "To make something move faster.",
    "access": "The ability or permission to use, enter, or look at something.",
    "accident": "Something that happens without a plan.",
    "accurate": "Correct or exact.",
    "achieve": "To complete a goal successfully.",
    "achievement": "Something completed successfully.",
    "acknowledge": "To accept or admit that something is true or exists.",
    "acquire": "To buy or get something.",
    "act": "To behave in a particular way.",
    "add": "To put things together.",
    "address": "The location where a building is or where a person lives.",
    "adequate": "Good enough.",
    "adjust": "To change something a little so it fits or works better.",
    "administrate": "To organize and manage something.",
    "adopt": "To choose and begin to use something.",
    "advice": "Words that tell someone what you think they should do.",
    "affect": "To cause a change in something.",
    "afford": "To have enough money or resources for something.",
    "after": "Later in time.",
    "again": "Once more.",
    "age": "How long something has existed or been alive.",
    "aggressive": "Ready to attack or act in a forceful, hostile way.",
    "ago": "At an earlier time.",
    "agree": "To have the same opinion or believe the same thing is true.",
    "air": "A mixture of gases with no color or smell.",
    "alert": "Awake and paying attention.",
    "allocate": "To set aside something for a particular purpose.",
    "alter": "To change something, usually in a small way.",
    "alternate": "To take turns.",
    "alternative": "Not the usual choice or method.",
    "altitude": "Height measured from sea level.",
    "always": "At all times or every time.",
    "amend": "To change something to improve it or fix a mistake.",
    "analyse": "To study something carefully in order to understand it.",
    "ancestor": "A person from whom someone is descended.",
    "ancient": "Very old, usually hundreds or thousands or millions of years old.",
    "animal": "A living thing that can move.",
    "annual": "Happening every year.",
    "answer": "Something someone says after being asked a question.",
    "antagonist": "An opponent or enemy.",
    "anticipate": "To think or do something about a future event before it happens.",
    "antonym": "A word with the opposite meaning of another word.",
    "anxious": "Worried or scared about what might happen in the future.",
    "apparent": "Easy to see, notice, or understand.",
    "appeal": "A strong or official request.",
    "approach": "A way of doing something.",
    "appropriate": "Right for the situation.",
    "approximate": "Close to the real number, length, time, or amount.",
    "arctic": "The region of Earth surrounding the North Pole.",
    "area": "A piece of land or space.",
    "arena": "A place for sports, entertainment, or other public events, with seats around it for people to watch.",
    "arrange": "To put something in order or organize it.",
    "arrest": "To stop something.",
    "arrive": "To come to a place, usually one you planned to go to.",
    "ascend": "To go up.",
    "ask": "To say something in order to get an answer.",
    "aspect": "A way of looking at something.",
    "assess": "To judge or measure someone or something.",
    "assist": "To help someone.",
    "assume": "To think something is true without enough information to know for sure.",
    "astound": "To shock or greatly surprise.",
    "attempt": "A try at something, usually something difficult.",
    "attention": "Careful focus of the mind.",
    "attentive": "Trying hard to notice things.",
    "attitude": "A person's feelings and opinions, especially as shown by actions.",
    "attract": "To make someone interested.",
    "attribute": "A part, feature, or characteristic.",
    "authority": "The power to make decisions.",
    "available": "Existing and able to be used.",
    "avalanche": "A large mass of snow and ice sliding quickly down a mountainside.",
    "average": "A measure in the middle of several numbers.",
    "avoid": "To stay away from something or not do it.",
    "aware": "Knowing about something.",
    "back": "The rear part of something.",
    "baggage": "Another word for luggage; bags and other containers that people use to carry things when they travel. Also, the things (most often clothes) carried in the bags.",
    "balance": "To make something have equal amounts on each side.",
    "ban": "A rule that stops something from happening.",
    "base": "The lower part that supports something.",
    "basic": "Simple.",
    "bed": "A piece of furniture to sleep on.",
    "before": "Earlier in time than something else.",
    "begin": "To start the first part of an action.",
    "behind": "At the back of something else.",
    "benefit": "Something good that comes from something else.",
    "between": "With one thing on one side and another on the other side.",
    "beverage": "A drink.",
    "big": "Large in size.",
    "blend": "To mix things so they combine.",
    "blizzard": "A heavy snowstorm with strong winds that make it hard to see.",
    "blossom": "A flower that later becomes fruit.",
    "blue": "Having the color of the sky on a clear day.",
    "board": "A flat surface.",
    "body": "The main part of a person, animal, object, or organization.",
    "bold": "Brave and willing to take risks.",
    "bond": "A close connection between people, often because of love or friendship.",
    "border": "The edge of a country where it meets another.",
    "both": "The first and the second of two things.",
    "bounce": "To change direction after hitting something.",
    "boy": "A male child or teenager.",
    "brave": "Not stopped by fear.",
    "brief": "Lasting a short time.",
    "bring": "To carry something with you to another place.",
    "budge": "To move from a fixed position.",
    "build": "To make something by putting pieces together.",
    "bungle": "To do something clumsily or incompletely.",
    "capable": "Able to do something.",
    "capacity": "How much a container, room, or other space can hold.",
    "capital": "The main city of a country, where the government is usually based.",
    "capture": "To catch a person or animal and keep them from escaping.",
    "care": "To look after someone.",
    "carry": "To lift something and move it to another place.",
    "category": "A group of people or things that are alike in some way.",
    "cause": "To make something happen.",
    "cautiously": "In a careful way.",
    "challenge": "Something difficult that you want or need to do.",
    "change": "To make something different.",
    "chapter": "A main division of a book.",
    "character": "The personal qualities that show what a person is like.",
    "check": "To look at something to see whether there is a problem or a change.",
    "chill": "A feeling of coldness.",
    "circular": "Having the shape of a circle.",
    "circumstance": "The facts around an action or event that help explain it.",
    "city": "A large town where many people live and work.",
    "civil": "Polite but not friendly.",
    "class": "A time for learning.",
    "clause": "A group of words that usually contains a subject and a predicate.",
    "clear": "Easy to see or hear.",
    "climate": "The weather conditions of a place.",
    "cling": "To hold on tightly.",
    "close": "Near, not far.",
    "coast": "The land closest to the sea.",
    "coax": "To gently persuade someone to do something.",
    "collect": "To bring things together.",
    "colour": "To give something a particular hue.",
    "column": "A tall support, often used in buildings.",
    "combine": "To put two or more things together.",
    "comment": "A short statement, usually giving an opinion.",
    "commission": "The official appointment of an officer in the armed forces.",
    "commit": "To do something illegal or wrong.",
    "common": "Found in large numbers or large amounts.",
    "communicate": "To make another person understand an idea, usually with words.",
    "community": "A group of people living in the same area or sharing similar interests or a similar background.",
    "companion": "Someone you spend time with because you enjoy being with them.",
    "compassion": "Awareness of another person's pain and a desire to help.",
    "compensate": "To give someone something because they lost something or did something for you.",
    "complete": "With everything included; entire, total.",
    "comply": "To act in the required way so that standards or rules are met.",
    "component": "One part that connects to other parts.",
    "compose": "To create or write something.",
    "compound": "A material made of several other materials.",
    "compute": "To calculate an answer.",
    "concept": "An idea.",
    "concern": "Something you think is a problem or needs attention.",
    "conclude": "To bring something to an end.",
    "conduct": "The way a person behaves.",
    "confer": "To give something to someone, often officially.",
    "confess": "To admit that you did something.",
    "confident": "Certain about something.",
    "confuse": "To mix things up in the mind.",
    "congratulate": "To tell someone they did well.",
    "consent": "Permission to do something.",
    "consequent": "Happening as a result of something else.",
    "consider": "To think carefully about something.",
    "considerable": "Fairly large or important.",
    "consist": "To be made of.",
    "constant": "Not changing over time.",
    "constitute": "To set up or establish something.",
    "constrain": "To force someone to follow a certain way of doing things.",
    "construct": "To make or build something by putting parts together.",
    "consult": "To ask someone for an opinion or advice.",
    "consume": "To eat or drink something.",
    "contain": "To keep something from getting out.",
    "content": "Happy and satisfied.",
    "context": "The situation around something.",
    "contract": "A legal agreement to trade goods, services, or property.",
    "contrary": "Opposite to something else.",
    "contrast": "A difference found when comparing things.",
    "contribute": "To give something so other people can use it.",
    "convene": "To come together to meet.",
    "convert": "To change something into a different form or use.",
    "convince": "To make someone believe or feel sure about something.",
    "cooperate": "To work together toward the same goal.",
    "coordinate": "To work together with someone to finish an activity.",
    "core": "The center part of something.",
    "corporate": "Related to a business or company.",
    "country": "Land controlled by a government.",
    "course": "The path something follows in space or time.",
    "courteous": "Polite and thoughtful toward others.",
    "cover": "To be over something so it cannot be seen.",
    "coward": "A person who lacks courage.",
    "crafty": "Very clever and skillful, often in a tricky way.",
    "crave": "To strongly want something.",
    "credit": "An arrangement that lets you buy now and pay later.",
    "crew": "A group of people working together to operate a ship, factory, airplane, or similar thing.",
    "criteria": "A set of principles used to judge or decide something.",
    "cross": "To go from one side of something to the other.",
    "culture": "A common history, set of beliefs, or way of life shared by a group.",
    "cut": "To make something shorter or divide it into pieces.",
    "data": "Information such as facts, numbers, or photographs.",
    "date": "A particular day in a month or year.",
    "debate": "An exchange of ideas about different sides of an issue.",
    "decide": "To choose one option when there are different things you could do.",
    "dedicate": "To present something to the public for the first time.",
    "deduce": "To reach a conclusion by logical thinking.",
    "deed": "An action that is done, sometimes a brave or important one.",
    "deep": "Going down a long way.",
    "define": "To state exactly what a word means.",
    "demonstrate": "To show that something is true or exists.",
    "dense": "Having parts close together or a lot of material in a small space.",
    "deposit": "To put something down in a place.",
    "deprive": "To keep something from someone.",
    "descend": "To go down.",
    "design": "To plan and show how something will look and work.",
    "desire": "A wish or feeling of want.",
    "destructive": "Causing destruction.",
    "detect": "To notice or find something by using the senses.",
    "develop": "To create something or make it better.",
    "diagram": "A drawing or sketch that shows how something works.",
    "differ": "To be different.",
    "digest": "To break down food in the stomach and intestines.",
    "dimension": "A direction of measurement in space, such as width, depth, or height.",
    "direct": "Straight and as short as possible.",
    "disaster": "A serious problem or event causing great harm.",
    "discrete": "Separate and distinct.",
    "distinct": "Clearly different or separate.",
    "distract": "To make someone pay attention to something else.",
    "distribute": "To divide something and give it out.",
    "diverse": "Made up of very different things or people.",
    "document": "A written record, often an official one.",
    "domain": "A field or area of knowledge, skill, or control.",
    "domestic": "Related to the home or to issues inside one country.",
    "dominate": "To have nearly complete control over something.",
    "don't": "The negative form of do.",
    "door": "A part of a wall that can be opened or closed to let people through.",
    "doze": "To sleep lightly or briefly.",
    "draw": "To make a picture with a pen, pencil, crayon, or similar tool.",
    "dry": "Having no water or liquid on it.",
    "during": "At the same time as something else.",
    "early": "Sooner than expected.",
    "earth": "The planet people live on.",
    "ease": "To lessen pain, worry, or trouble.",
    "east": "The direction where the sun rises.",
    "economy": "The use of the resources of a community or system.",
    "element": "One part of something bigger.",
    "emerge": "To come out of something.",
    "emphasis": "Special attention or importance given to something.",
    "enable": "To make someone or something able to do something.",
    "end": "The last part or final one in a group.",
    "energy": "The ability to do work, move things, or produce heat or light.",
    "enforce": "To make sure a rule or law is followed.",
    "enough": "As much or as many as needed.",
    "ensure": "To make sure something is correct or happens.",
    "entertain": "To keep someone interested.",
    "entire": "Whole, with every part included.",
    "entity": "A whole thing that exists independently.",
    "entrance": "A way into a place, such as a door or gate.",
    "envy": "A feeling of wanting what someone else has.",
    "equate": "To consider two things equal.",
    "equivalent": "Equal in value or acceptability.",
    "erupt": "To burst out violently.",
    "escalate": "To increase in intensity.",
    "essential": "Very important.",
    "establish": "To start something with the intention that it will last.",
    "estate": "Everything someone owns, especially what is left after death.",
    "estimate": "To guess a number, size, or amount using limited information.",
    "ethnic": "Related to a group connected by race, culture, or nationality.",
    "evade": "To try to avoid or get away from something.",
    "evaluate": "To judge someone or something.",
    "even": "Able to be divided into two equal whole-number parts.",
    "ever": "At any time.",
    "every": "All the people, things, or times in a group.",
    "evident": "Very easy to notice or understand.",
    "evolve": "To change slowly over a long time.",
    "examine": "To look at something carefully.",
    "example": "A model showing what something of the same kind is like.",
    "exasperate": "To irritate or frustrate someone severely.",
    "exceed": "To go beyond a limit or allowed amount.",
    "exclude": "To keep someone or something out.",
    "exert": "To use a lot of strength or effort.",
    "exhibit": "To show something to others.",
    "expand": "To become bigger.",
    "explore": "To think carefully about a possibility, plan, or idea.",
    "export": "To send goods out of a country for sale.",
    "extend": "To make something longer.",
    "external": "On the outside.",
    "extraordinary": "Far above the ordinary; very unusual or impressive.",
    "face": "The front part of the head.",
    "facilitate": "To make something easier.",
    "fact": "A piece of information that is true.",
    "factor": "One thing that helps cause a result.",
    "family": "A group of people related by blood or marriage.",
    "far": "A long distance away.",
    "father": "A male parent.",
    "feature": "A special or noticeable part of something.",
    "feel": "To have a strong sense that something is true.",
    "feet": "More than one foot.",
    "few": "Not many.",
    "fierce": "Violent or aggressive.",
    "fill": "To put something in until no space is left.",
    "final": "Last.",
    "finance": "Activities related to money, banking, and government spending.",
    "fire": "A reaction that produces heat and flames.",
    "fish": "An animal with scales and gills that lives in water.",
    "flexible": "Able to bend.",
    "focus": "To pay special attention to something.",
    "follow": "To come after something else.",
    "food": "What people and animals eat.",
    "foot": "The part at the end of the leg used for standing and walking.",
    "force": "A push or pull, or the strength of that push or pull.",
    "formula": "A fixed way of doing something or solving a problem.",
    "fragile": "Easy to break.",
    "frail": "Weak and easy to be harmed.",
    "framework": "The basic ideas or structure that supports something else.",
    "frantic": "Very worried or upset because of fear or stress.",
    "free": "Costing no money.",
    "frequent": "Happening many times in a short period.",
    "friend": "A person you like, enjoy being with, and help, but who is not related to you.",
    "full": "Holding as much as possible.",
    "function": "A purpose or job.",
    "fund": "An amount of money kept for a specific purpose.",
    "fundamental": "Basic and important.",
    "furious": "Very angry.",
    "game": "An activity people do for fun.",
    "gasp": "To take in breath suddenly.",
    "generate": "To create something.",
    "generation": "The average time between parents being born and their children being born.",
    "get": "To receive or obtain.",
    "gigantic": "Very, very large.",
    "give": "To let another person have something that was yours.",
    "glide": "To move smoothly with little effort.",
    "globe": "The Earth.",
    "goal": "Something you want to do or be able to do.",
    "gold": "A valuable yellow metal with symbol Au and atomic number 79.",
    "good": "Kind, helpful, and doing what is right.",
    "grant": "To give something, usually officially.",
    "grasp": "To hold something tightly.",
    "great": "Very good.",
    "ground": "Earth or soil.",
    "group": "More than two people or things together.",
    "grow": "To become bigger or change over time.",
    "habit": "Something you do regularly.",
    "habitat": "The natural place where a plant or animal lives.",
    "half": "One of two equal parts.",
    "hand": "The part at the end of the arm with fingers and a thumb.",
    "happen": "To take place or change without a plan.",
    "hard": "Not soft.",
    "hazy": "Not clear because of mist or haze.",
    "head": "The highest and most important part of the body.",
    "hear": "To notice a sound with the ear.",
    "hearty": "Healthy and full of energy.",
    "help": "To make something easier for someone or do part of it for them.",
    "hence": "for this reason",
    "here": "(in, at or to) this place",
    "high": "A long way up.",
    "home": "The place where a person lives and sleeps.",
    "homonym": "One of two words that sound and are spelled the same.",
    "horse": "A large hoofed mammal that people often ride.",
    "house": "A building where one family lives.",
    "humble": "Aware of your own weaknesses and not seeking praise.",
    "idea": "A thought or concept.",
    "identical": "Exactly the same.",
    "ignorance": "A lack of knowledge.",
    "illuminate": "To shine light on something.",
    "illustrate": "To draw a picture of something or explain it.",
    "image": "Something you can see or imagine that looks like the real thing.",
    "immense": "Very large or big.",
    "immigrate": "To move to a country to live there.",
    "impact": "The effect of an act, statement, or change.",
    "implement": "To put a plan into action.",
    "implicate": "To connect someone or something to something else, possibly as a cause.",
    "imply": "To mean something without saying it directly.",
    "impose": "To force something on someone.",
    "impressive": "Making a strong positive impression.",
    "inch": "A unit of length equal to 2.54 centimetres.",
    "incidence": "How often something happens.",
    "income": "Money received from work or other sources.",
    "increase": "To become bigger or greater.",
    "independent": "Free and not controlled or dependent on something else.",
    "indicate": "To point something out or draw attention to it.",
    "individual": "A single person considered separately from others.",
    "inhibit": "To stop something from happening or make it happen less.",
    "initial": "Near the beginning.",
    "injure": "To hurt a person or animal.",
    "inspire": "To give someone ideas or make them want to create.",
    "instance": "A time or situation when something happens.",
    "instant": "Ready very quickly or happening very quickly.",
    "institute": "An organization such as a school or hospital that does teaching or research.",
    "integrate": "To combine things into one whole.",
    "intense": "Having a very strong action or effect.",
    "interact": "To communicate or work with someone or something else.",
    "intercept": "To stop or divert something while it is moving or happening.",
    "interest": "A desire to know more about something or liking for it.",
    "internal": "within or inside",
    "interpret": "To understand a particular meaning in something and perhaps explain it.",
    "invest": "To spend time or money to improve something.",
    "investigate": "To gather information and think carefully about a problem to find an answer.",
    "invisible": "Unable to be seen.",
    "involve": "To include something as part of an activity.",
    "island": "A piece of land completely surrounded by water.",
    "issue": "A topic or problem people are discussing.",
    "jagged": "Unevenly cut or covered with sharp points.",
    "journal": "A record of what is happening, often written regularly.",
    "journey": "A long trip.",
    "justify": "To explain why something was right or necessary.",
    "keep": "To make something safe or continue having it.",
    "kind": "Good for another person.",
    "label": "A small sign, usually on something, that tells you about it.",
    "labor": "To work hard.",
    "lack": "Not enough of something, or none at all.",
    "land": "The part of Earth that is not covered with water.",
    "language": "The words and grammar used by a group of people so they can understand each other.",
    "large": "Big; of great size.",
    "last": "Coming after all the others.",
    "late": "Happening after the expected or planned time.",
    "laugh": "To make sounds like \"ha ha\" because something is funny.",
    "launch": "To start something or get it going.",
    "layer": "A covering material or substance.",
    "leave": "To go away from a place.",
    "left": "The side opposite the right side.",
    "legal": "Allowed by law.",
    "legislate": "To create or change a law.",
    "less": "A smaller amount or degree.",
    "let": "To allow someone to do something.",
    "letter": "A written message or note.",
    "liberal": "Allowing change, flexibility, and free thought.",
    "license": "To give official permission.",
    "life": "The time during which a person, animal, or plant is alive.",
    "light": "The energy seen by the eyes.",
    "limb": "An arm or a leg.",
    "limit": "The point beyond which something cannot go.",
    "limp": "To walk unevenly because one leg is hurt or weak.",
    "line": "A long, thin mark.",
    "list": "A group of related words or items written one after another.",
    "little": "Not big in size.",
    "live": "To be alive.",
    "logic": "A careful step-by-step way of thinking about truth.",
    "lot": "To a large degree.",
    "low": "Close to the ground.",
    "loyal": "True and faithful to someone.",
    "main": "Most important or biggest.",
    "maintain": "To keep something at the same level or in good condition.",
    "major": "Big and important.",
    "man": "An adult male human.",
    "manufacture": "To make something, usually in a factory.",
    "margin": "The empty space at the side of a page.",
    "mark": "A line or small spot left on something.",
    "massive": "Very big.",
    "master": "To become very skilled at something.",
    "mature": "Fully developed.",
    "maximise": "To make something as large as possible.",
    "measure": "To calculate size, mass, temperature, or another quantity using units.",
    "mechanism": "The way something works.",
    "medical": "About physical health and medicine.",
    "men": "More than one man.",
    "mental": "Related to the mind and thinking.",
    "method": "A planned way of doing something.",
    "migrate": "To move from one place to another, usually for something better.",
    "mind": "The part of a person that thinks.",
    "minor": "Not very important.",
    "minute": "A unit of time equal to sixty seconds.",
    "mischief": "Minor trouble or the intention to cause it.",
    "miss": "To fail to hit something.",
    "mistrust": "To believe someone is not honest or trustworthy.",
    "mock": "To copy someone's actions in an unkind way.",
    "modify": "To change something, often only a little.",
    "moon": "The bright object that goes around Earth and can be seen at night.",
    "morning": "Period between sunrise to midday.",
    "mother": "A female parent.",
    "mountain": "A very high natural rise of the Earth's surface.",
    "move": "To go from one place to another.",
    "much": "a lot of; a large amount of; a high degree",
    "must": "Used to say something is necessary or required.",
    "mystify": "To confuse someone completely.",
    "nation": "A country or political entity.",
    "near": "Close.",
    "need": "To want something because it is necessary.",
    "negate": "To cancel or remove the effect of something.",
    "network": "A group of connections between points.",
    "never": "At no time.",
    "new": "Not old.",
    "next": "Coming after this one.",
    "night": "The part of the day from dusk to dawn.",
    "noble": "Having qualities admired by others.",
    "north": "The direction opposite south.",
    "nothing": "Not anything.",
    "notion": "An idea.",
    "numeral": "A symbol or word that represents a number.",
    "numerous": "Existing in large numbers.",
    "nursery": "A place where young plants are grown before being planted outdoors.",
    "oasis": "A place in a desert with water and plant life.",
    "object": "A thing that can be touched and is not alive.",
    "objective": "Based on facts rather than feelings.",
    "observe": "To watch something carefully.",
    "obsolete": "No longer used because something newer replaced it.",
    "obtain": "To get something.",
    "obvious": "Easy to see, think of, or understand.",
    "occasion": "A particular time.",
    "occupy": "To take up a space or live in a place.",
    "occur": "To happen.",
    "off": "Away from somewhere or some time.",
    "often": "Many times.",
    "old": "Not young; having existed a long time.",
    "once": "one time",
    "open": "Not closed.",
    "opposite": "Completely different from, or across from, something else.",
    "option": "A choice.",
    "orchard": "An area where fruit trees are grown.",
    "ordeal": "A very unpleasant experience.",
    "order": "A state in which things are arranged as they should be.",
    "orient": "To point something in a certain direction.",
    "origin": "The place where something comes from.",
    "other": "Different from the one already mentioned.",
    "outcome": "The result of an action or situation.",
    "output": "What is produced by a worker, machine, or computer.",
    "outstanding": "Better than others, usually in a good way.",
    "overall": "Covering everything in a general way.",
    "overthrow": "To remove someone from power by force.",
    "own": "To have something that belongs to you.",
    "page": "One side of a sheet of paper in a book, newspaper, or similar item.",
    "parallel": "Going in the same direction and staying the same distance apart.",
    "part": "One piece or a small amount of something.",
    "participate": "To join in and take part.",
    "partner": "A person joined with another for business, sport, or a relationship.",
    "pass": "To move so something that was in front of you is now behind you.",
    "passage": "A short section from a book or other piece of writing.",
    "pastime": "An activity done for enjoyment or to fill time.",
    "pasture": "Land covered with grass where animals feed.",
    "pause": "A short stop in an activity.",
    "peculiar": "Unusual or out of the ordinary.",
    "pedestrian": "A person walking on foot.",
    "peer": "Someone of the same level as you.",
    "perceive": "To notice something through the senses or become aware of it.",
    "percent": "The number of parts out of a hundred.",
    "perform": "To do something.",
    "period": "A length of time.",
    "perish": "To die.",
    "perspective": "A way of looking at or thinking about something.",
    "phase": "A stage in a process.",
    "philosophy": "The study of existence, truth, and how people should live.",
    "physical": "Related to the body or to things that can be touched.",
    "picture": "A still or moving image on a screen or surface.",
    "piece": "A part of something that can be or has been separated.",
    "place": "An area of land or a location.",
    "plain": "Simple and undecorated.",
    "plane": "A vehicle with wings that flies.",
    "plant": "A living thing that grows in one place and usually has leaves and roots.",
    "plead": "To ask for something in a strong and emotional way.",
    "plunge": "To dive or jump quickly into something.",
    "point": "The sharp end of something.",
    "policy": "An official rule or plan for how to act.",
    "portable": "Easy to carry or move.",
    "positive": "Good, happy, or wanted.",
    "possess": "To have or own.",
    "possible": "Able to be done.",
    "potential": "The ability to become very good or successful in the future.",
    "practice": "To do something again and again to improve.",
    "precise": "Correct and exact.",
    "predict": "To say something will happen before it is observed.",
    "prefer": "To like one thing more than another.",
    "prejudice": "A belief, often negative, formed before knowing the facts.",
    "prepare": "To get something ready.",
    "preserve": "To keep something from decay or loss.",
    "press": "To push something against something else.",
    "presume": "To believe something is true without proof.",
    "prevent": "To stop something from happening.",
    "previous": "Happening before a particular time.",
    "price": "The amount of money needed to buy something.",
    "primary": "First.",
    "prime": "Best, most important, or number one.",
    "principal": "Main or most important.",
    "prior": "Occurring before.",
    "problem": "Something difficult to do, understand, or solve.",
    "proceed": "To go forward with something.",
    "process": "A series of steps taken for a purpose.",
    "produce": "To make, create, or cause something to come out.",
    "product": "A substance made by a chemical reaction.",
    "professional": "Doing a job seriously and skillfully.",
    "project": "A complex job or assignment, often involving research or construction.",
    "promote": "To help something or someone become bigger, higher, or more popular.",
    "proportion": "The size relationship between one part and another.",
    "protagonist": "The main character in a story or drama.",
    "provide": "To give what is needed.",
    "psychology": "The study of the mind and behaviour.",
    "publish": "To make a book, article, song, or similar work available to others.",
    "purchase": "To buy something.",
    "pursue": "To try to reach, catch, or get someone or something.",
    "put": "To move something to a place.",
    "queasy": "Feeling sick to the stomach.",
    "question": "Something someone says in order to get an answer.",
    "range": "The area between an upper and lower limit.",
    "ratio": "A comparison between two amounts, written x:y.",
    "react": "To respond because of something that happened.",
    "read": "To look at writing and understand it.",
    "ready": "Prepared.",
    "real": "True and not imagined.",
    "recall": "To remember something from the past.",
    "recent": "Happening a short time ago.",
    "recognise": "To know what something is because you have seen or known it before.",
    "reduce": "To make something smaller or less.",
    "regime": "A plan or system.",
    "region": "An area of land or part of the body.",
    "regulate": "To control something through rules or laws.",
    "release": "To let go of something and set it free.",
    "relevant": "Meaningfully connected to the topic.",
    "rely": "To need and trust someone or something.",
    "remark": "To say what you noticed or think.",
    "remember": "To keep something in mind or bring it back to mind later.",
    "represent": "To stand in the place of something or act for it.",
    "request": "The act of asking for something, sometimes formally.",
    "require": "To need something.",
    "resemble": "To be similar to something else.",
    "reside": "To live in a place or be located there.",
    "resident": "Someone who lives in a particular area.",
    "resist": "To fight, push, or work against something.",
    "resolve": "To make a firm decision to do something.",
    "resource": "Something useful that is available.",
    "respect": "To think someone is worthy or admirable.",
    "respond": "To do or say something in reaction to something else.",
    "response": "Words or actions given in reaction to something else.",
    "responsible": "Making good decisions and making sure important things get done.",
    "restrict": "To limit something.",
    "retain": "To keep something.",
    "retire": "To stop working, usually because of age.",
    "retrieve": "To go and get something back.",
    "reveal": "To show or make known something that was hidden.",
    "revenue": "Money received by a business or government.",
    "reverse": "To make something move or act in the opposite direction.",
    "revert": "To go back to an earlier state or undo a change.",
    "right": "Correct.",
    "rigorous": "Very strict, exact, and unwilling to relax the rules.",
    "risk": "The chance that something bad may happen.",
    "rock": "A hard natural substance in the Earth's surface.",
    "room": "A part of a building enclosed by walls.",
    "round": "Curved like a circle, not straight.",
    "route": "The way from one place to another.",
    "same": "Exactly alike.",
    "saunter": "To walk slowly and in a relaxed way.",
    "save": "To keep something and not give it away or lose it.",
    "say": "To express something in words.",
    "scatter": "To separate and go in different directions.",
    "schedule": "A plan showing what happens and when.",
    "scheme": "A plan, sometimes a dishonest one.",
    "second": "Number two in order.",
    "section": "A part of something.",
    "sector": "A division of an area or part of the economy.",
    "secure": "Firmly held in place and unlikely to fall or change.",
    "seem": "To appear to be a certain way.",
    "seldom": "Almost never.",
    "senseless": "Having no meaning or purpose.",
    "sentence": "A group of words that follows grammar rules and expresses a complete thought.",
    "sequence": "A set of things in a specific order.",
    "series": "A set of related programs, books, or events.",
    "set": "To put something in a place.",
    "sever": "To cut through or separate completely.",
    "severe": "Harsh, strict, or very serious.",
    "shabby": "Torn or worn out.",
    "shallow": "Not thinking deeply and caring only about obvious things.",
    "shape": "The outer form of something.",
    "shift": "To move.",
    "ship": "A large boat.",
    "short": "Having a small distance from bottom to top; not long.",
    "should": "Used to say that something is a good idea.",
    "show": "To make something easy to see.",
    "significant": "Important or large enough to matter.",
    "similar": "Almost the same in many ways.",
    "since": "From a time in the past until now or another later time.",
    "size": "How big or small something is.",
    "sluggish": "Lazy or slow to act.",
    "small": "Not big.",
    "snow": "White frozen water that falls from the sky.",
    "soar": "To fly high with little or no effort.",
    "solar": "Related to the sun.",
    "solitary": "Living alone or without company.",
    "solo": "Done alone.",
    "song": "Music with words.",
    "soon": "A short time after now or after another time.",
    "soothe": "To calm or relieve someone.",
    "source": "The place something came from originally.",
    "south": "The direction opposite north.",
    "special": "Not usual; different or important.",
    "specific": "Clearly identified and not general.",
    "specify": "To say exactly which one or how something should be done.",
    "spell": "To say or write the letters of a word in order.",
    "spoil": "To ruin something or make it no good.",
    "stable": "Unlikely to move or change.",
    "stand": "To be upright on your feet.",
    "start": "To begin.",
    "starve": "To die from not having enough food.",
    "state": "A condition or situation.",
    "stationary": "Not moving.",
    "statistic": "A number that describes information.",
    "stay": "To remain in a place.",
    "steer": "To control which direction something travels.",
    "still": "Not moving.",
    "stop": "To come to an end or cease doing something.",
    "story": "A piece of writing about real or fictional events.",
    "street": "A road in a city with buildings along it.",
    "stress": "Emotional pressure caused by worry.",
    "strive": "To try very hard.",
    "strong": "Having a lot of physical power.",
    "structure": "The way something is put together.",
    "study": "To make an effort to learn something.",
    "style": "A particular look, design, or way of doing something.",
    "subsequent": "Happening after something else.",
    "substitute": "A person who takes the place of another, especially in sport or teaching.",
    "such": "Of the kind already mentioned.",
    "sufficient": "Enough or good enough.",
    "suffix": "An ending added to a word that changes meaning or grammar.",
    "suffocate": "To die from lack of air.",
    "suitable": "Right for a particular purpose.",
    "summary": "A short explanation of a longer text or idea.",
    "summit": "The highest point of a mountain.",
    "superior": "Better than something else.",
    "supplement": "An extra thing added to something.",
    "sure": "Certain.",
    "surface": "The outside of an object.",
    "survey": "To ask many people questions in a formal way.",
    "suspend": "To stop something for a time.",
    "sustain": "To keep something going or maintain it.",
    "swarm": "A large group of insects, especially flying ones.",
    "swift": "Fast.",
    "symbol": "A person or object that represents an idea or group.",
    "synonym": "A word with the same meaning as another word.",
    "tail": "A long, thin part at the back of an animal.",
    "take": "To bring or move someone or something from one place to another.",
    "talk": "To speak.",
    "talon": "A large sharp claw of a bird of prey.",
    "taunt": "To make sarcastic remarks to make someone angry.",
    "technical": "Related to special knowledge or skill.",
    "technique": "A skillful or specialized way of doing something.",
    "technology": "Tools, equipment, and activities that come from scientific knowledge.",
    "tell": "To speak to someone about a fact or idea.",
    "terror": "Very strong fear.",
    "test": "Something done to see whether something works.",
    "theory": "An idea that tries to explain an observation.",
    "think": "To have words or ideas in the mind without saying them out loud.",
    "those": "The plural form of that.",
    "thought": "An idea or concept in the mind.",
    "thousand": "The number 1,000.",
    "three": "The number 3.",
    "together": "Well organized and focused.",
    "tour": "A planned trip to look at a place.",
    "tradition": "Something done in the same way for a long time.",
    "tragic": "Causing great pain and suffering.",
    "transfer": "To move something to a different place.",
    "transit": "The movement of goods or people from one place to another.",
    "travel": "To go on a journey or visit places.",
    "tree": "A tall plant made of wood.",
    "trend": "A general movement or change in one direction.",
    "triumph": "A great success.",
    "true": "Correct or real, not imagined.",
    "turn": "To face a different direction.",
    "typical": "Normal and expected.",
    "under": "In the same place as another thing, but lower.",
    "undertake": "To take responsibility for something and begin doing it.",
    "until": "Up to a particular time.",
    "us": "The speaker and one or more other people.",
    "usual": "Happening often or being normal.",
    "utilise": "To make use of something.",
    "valiant": "Showing courage.",
    "valid": "Correct, acceptable, and appropriate.",
    "value": "How good or important something is, or how much money it is worth.",
    "variety": "A group of things that are not all the same.",
    "vary": "To be different at different times or in different situations.",
    "vast": "Very, very big.",
    "venture": "An undertaking or risky project.",
    "version": "One form of something that exists in several forms.",
    "very": "Used to make an adjective or adverb stronger.",
    "visible": "Able to be seen.",
    "vision": "The ability to see.",
    "vivid": "Very bright or deep in color.",
    "volume": "How loud a sound is.",
    "volunteer": "To do something willingly without payment.",
    "wander": "To walk or move slowly without a clear purpose.",
    "want": "To think you would be happier if you had or did something.",
    "watch": "To look at someone or something for a while.",
    "weary": "Very tired.",
    "weight": "How heavy something is.",
    "welfare": "A person's health, safety, and happiness.",
    "well": "In a good way.",
    "wheel": "A round part of a vehicle that turns and touches the ground.",
    "when": "At what time.",
    "where": "In or to what place.",
    "while": "At the same time as.",
    "whole": "All of something; entire.",
    "why": "Used to ask the reason for something.",
    "wind": "Moving air.",
    "withdraw": "To take something out from somewhere.",
    "wonder": "To think about something because you want to know more.",
    "wood": "The material trees are made of.",
    "work": "A person's job.",
    "world": "The Earth.",
    "year": "A period of twelve months.",
    "young": "Not old; not having lived long.",
    "your": "Belonging to you.",
};
