import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = path.join(rootDir, 'vocab_definitions');
const outputPath = path.join(rootDir, 'src', 'generated', 'vocab.ts');
const checkOnly = process.argv.includes('--check');

const REQUIRED_KEYS = ['word', 'difficulty', 'definition', 'example', 'synonyms', 'antonyms'];
const DIFFICULTIES = new Set([
    'reception',
    'year1',
    'year2',
    'year3',
    'year4',
    'year5',
    'year6',
    'year6Plus',
    'year6PlusPlus',
]);

function slug(word) {
    return word.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function parseDefinitionFile(fileName, expectedIndex) {
    const match = /^(\d{3})_(.+)\.ts$/.exec(fileName);
    if (!match) {
        throw new Error(`${fileName}: expected a name like 001_word.ts`);
    }

    const index = Number(match[1]);
    if (index !== expectedIndex) {
        throw new Error(`${fileName}: expected index ${String(expectedIndex).padStart(3, '0')}`);
    }

    const source = fs.readFileSync(path.join(sourceDir, fileName), 'utf8');
    const exportMatches = source.match(/\bexport\s+default\b/g) ?? [];
    if (exportMatches.length !== 1) {
        throw new Error(`${fileName}: expected exactly one default export`);
    }

    const expression = source.replace(/^\s*export\s+default\s*/, '').replace(/;\s*$/, '');
    const entry = vm.runInNewContext(`(${expression})`);
    for (const key of REQUIRED_KEYS) {
        if (!(key in entry)) {
            throw new Error(`${fileName}: missing ${key}`);
        }
    }
    if (match[2] !== slug(entry.word)) {
        throw new Error(`${fileName}: slug does not match word ${entry.word}`);
    }
    if (!DIFFICULTIES.has(entry.difficulty)) {
        throw new Error(`${fileName}: unknown difficulty ${entry.difficulty}`);
    }
    if (!String(entry.definition).trim()) {
        throw new Error(`${fileName}: blank definition`);
    }
    if (!String(entry.example).trim()) {
        throw new Error(`${fileName}: blank example`);
    }
    if (!Array.isArray(entry.synonyms)) {
        throw new Error(`${fileName}: synonyms must be an array`);
    }
    if (!Array.isArray(entry.antonyms)) {
        throw new Error(`${fileName}: antonyms must be an array`);
    }

    return entry;
}

function formatArray(values) {
    return `[${values.map((value) => JSON.stringify(value)).join(', ')}]`;
}

function formatEntry(entry) {
    return [
        '    {',
        `        word: ${JSON.stringify(entry.word)},`,
        `        difficulty: ${JSON.stringify(entry.difficulty)},`,
        `        definition: ${JSON.stringify(entry.definition)},`,
        `        example: ${JSON.stringify(entry.example)},`,
        `        synonyms: ${formatArray(entry.synonyms)},`,
        `        antonyms: ${formatArray(entry.antonyms)},`,
        '    },',
    ].join('\n');
}

const files = fs.readdirSync(sourceDir)
    .filter((fileName) => fileName.endsWith('.ts'))
    .sort((left, right) => left.localeCompare(right));

if (files.length === 0) {
    throw new Error(`No vocabulary definition files found in ${sourceDir}`);
}

const entries = files.map((fileName, index) => parseDefinitionFile(fileName, index + 1));
const output = `${[
    "import type { WordEntry } from '../../gameTypes';",
    '',
    '// This file is generated by scripts/build-vocab.mjs from vocab_definitions/.',
    '// Do not edit by hand.',
    'export const ALL_VOCAB: WordEntry[] = [',
    entries.map(formatEntry).join('\n'),
    '];',
    '',
].join('\n')}`;

if (!checkOnly) {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, output);
}

console.log(`${checkOnly ? 'Checked' : 'Generated'} ${entries.length} vocabulary entries from ${files.length} files.`);