import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = path.join(rootDir, 'vocab_definitions');
const outputPath = path.join(rootDir, 'src', 'generated', 'vocab.ts');
const checkOnly = process.argv.includes('--check');

const REQUIRED_KEYS = ['word', 'difficulty', 'definition', 'example', 'synonyms', 'antonyms'];
const DIFFICULTIES = new Set([
    'reception',
    'year1',
    'year2',
    'year3',
    'year4',
    'year5',
    'year6',
    'year6Plus',
    'year6PlusPlus',
]);
const DIFFICULTY_DIRECTORIES = {
    reception: 'reception',
    year1: 'year_1',
    year2: 'year_2',
    year3: 'year_3',
    year4: 'year_4',
    year5: 'year_5',
    year6: 'year_6',
    year6Plus: 'year_6_plus',
    year6PlusPlus: 'year_6_plus_plus',
};

function slug(word) {
    return word.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function parseDefinitionFile(relativePath, expectedIndex) {
    const fileName = path.basename(relativePath);
    const match = /^(\d{3})_(.+)\.ts$/.exec(fileName);
    if (!match) {
        throw new Error(`${relativePath}: expected a name like 001_word.ts`);
    }

    const index = Number(match[1]);
    if (index !== expectedIndex) {
        throw new Error(`${relativePath}: expected index ${String(expectedIndex).padStart(3, '0')}`);
    }

    const source = fs.readFileSync(path.join(sourceDir, relativePath), 'utf8');
    const exportMatches = source.match(/\bexport\s+default\b/g) ?? [];
    if (exportMatches.length !== 1) {
        throw new Error(`${relativePath}: expected exactly one default export`);
    }

    const expression = source.replace(/^\s*export\s+default\s*/, '').replace(/;\s*$/, '');
    const entry = vm.runInNewContext(`(${expression})`);
    for (const key of REQUIRED_KEYS) {
        if (!(key in entry)) {
            throw new Error(`${relativePath}: missing ${key}`);
        }
    }
    if (match[2] !== slug(entry.word)) {
        throw new Error(`${relativePath}: slug does not match word ${entry.word}`);
    }
    if (!DIFFICULTIES.has(entry.difficulty)) {
        throw new Error(`${relativePath}: unknown difficulty ${entry.difficulty}`);
    }

    const expectedDirectory = DIFFICULTY_DIRECTORIES[entry.difficulty];
    const actualDirectory = path.dirname(relativePath);
    if (actualDirectory !== expectedDirectory) {
        throw new Error(`${relativePath}: expected to live in ${expectedDirectory}/ for difficulty ${entry.difficulty}`);
    }
    if (!String(entry.definition).trim()) {
        throw new Error(`${relativePath}: blank definition`);
    }
    if (!String(entry.example).trim()) {
        throw new Error(`${relativePath}: blank example`);
    }
    if (!Array.isArray(entry.synonyms)) {
        throw new Error(`${relativePath}: synonyms must be an array`);
    }
    if (!Array.isArray(entry.antonyms)) {
        throw new Error(`${relativePath}: antonyms must be an array`);
    }

    return entry;
}

function listDefinitionFiles(currentDir, relativeDir = '') {
    return fs.readdirSync(currentDir, { withFileTypes: true })
        .flatMap((entry) => {
            const relativePath = path.join(relativeDir, entry.name);
            const absolutePath = path.join(currentDir, entry.name);

            if (entry.isDirectory()) {
                return listDefinitionFiles(absolutePath, relativePath);
            }

            return entry.name.endsWith('.ts') ? [relativePath] : [];
        });
}

function fileIndex(relativePath) {
    const match = /^(\d{3})_/.exec(path.basename(relativePath));
    if (!match) {
        throw new Error(`${relativePath}: expected a name like 001_word.ts`);
    }

    return Number(match[1]);
}

function formatArray(values) {
    return `[${values.map((value) => JSON.stringify(value)).join(', ')}]`;
}

function formatEntry(entry) {
    return [
        '    {',
        `        word: ${JSON.stringify(entry.word)},`,
        `        difficulty: ${JSON.stringify(entry.difficulty)},`,
        `        definition: ${JSON.stringify(entry.definition)},`,
        `        example: ${JSON.stringify(entry.example)},`,
        `        synonyms: ${formatArray(entry.synonyms)},`,
        `        antonyms: ${formatArray(entry.antonyms)},`,
        '    },',
    ].join('\n');
}

const files = listDefinitionFiles(sourceDir)
    .sort((left, right) => fileIndex(left) - fileIndex(right));

if (files.length === 0) {
    throw new Error(`No vocabulary definition files found in ${sourceDir}`);
}

const entries = files.map((fileName, index) => parseDefinitionFile(fileName, index + 1));
const output = `${[
    "import type { WordEntry } from '../../gameTypes';",
    '',
    '// This file is generated by scripts/build-vocab.mjs from vocab_definitions/.',
    '// Do not edit by hand.',
    'export const ALL_VOCAB: WordEntry[] = [',
    entries.map(formatEntry).join('\n'),
    '];',
    '',
].join('\n')}`;

if (!checkOnly) {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, output);
}

console.log(`${checkOnly ? 'Checked' : 'Generated'} ${entries.length} vocabulary entries from ${files.length} files.`);